### ISSUE TITLE
Usage example is not fully functional

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#58]
- [x] An example config file needs to be provided, or we should explain how/where to create/find it
- [ ] All config values must be defined and explained

**Comment by epifanio** [comment]
Trying to run the container - following the directions in the readme, I got the following error:


```
ERROR    Config value 'rejected_jobs_path' must be set
```

I used the default config.yaml file - any clue on  what is missing?

**Comment by epifanio** [comment]
I see the following [example_config.yaml](https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/example_config.yaml) has an entry for `rejected_jobs_path` 

I set it to a directory on my filesystem and use it as follow:

```
podman run --rm -ti -p 9999:8000 -v config.yml:/config.yml:ro -v $(pwd)/workdir:/workdir -v $(pwd)/rejected_jobs_path:/rejected_jobs_path localhost/dmci:latest
```

my config looks like:

```
---
dmci:
  distributors:
    - pycsw
    - file
  distributor_cache: /workdir
  max_permitted_size: 100000
  rejected_jobs_path: /rejected_jobs_path
  mmd_xslt_path: /usr/share/mmd/xslt/mmd-to-geonorge.xslt
  mmd_xsd_path: /usr/share/mmd/xsd/mmd_strict.xsd

pycsw:
  csw_service_url: https://tstsios.csw.met.no/csw

file:
  file_archive_path: /workdir
```

But the error persist

**Comment by epifanio** [comment]
Any update on this?

**Comment by mortenwh** [comment]
Try a config like this one:
```
dmci:
  distributors:
    - file
      #- pycsw
  distributor_cache: /home/mortenwh/tmp
  rejected_jobs_path: .
  max_permitted_size: 100000
  mmd_xslt_path: ../mmd/xslt/mmd-to-geonorge.xslt
  mmd_xsd_path: ../mmd/xsd/mmd_strict.xsd #or mmd.xsd

pycsw:
  csw_service_url: http://localhost

file:
  file_archive_path: /home/mortenwh/tmp
```

We're working on an update of the docs - what is the status @johtoblan ?
